### ISSUE TITLE
Server Crashes when loading the config

### ISSUE THREAD

**Issue by P4NC00Nexe** [GeheimagentNr1/DiscordIntegration#20] opened 2022-10-01 21:29 UTC
**Versions**
Minecraft Version: 1.19.2
Minecraft Forge Version: 43.1.24
Mod Version: 2.2.1

**Log files**
https://gist.github.com/P4NC00Nexe/f59a8cf7e89f5168e29112e82ecd3c09

**Describe the bug**
Server crashes when loading the config. Server Error "Exception in server tick loop"

**To Reproduce**
1. Add mod
2. start server
3. shut down server
4. edit config
5. start server
6. server crashes

**Expected behavior**
I expected the server to launch smoothly

[crash-2022-10-01_21.19.42-server.txt](https://github.com/GeheimagentNr1/DiscordIntegration/files/9691230/crash-2022-10-01_21.19.42-server.txt)
[latest.log](https://github.com/GeheimagentNr1/DiscordIntegration/files/9691231/latest.log)
[debug.log](https://github.com/GeheimagentNr1/DiscordIntegration/files/9691236/debug.log)

**Comment by GeheimagentNr1** [comment] 2022-10-09 08:11
<table><tbody><tr><th>Status:</th><td>Won't fix Nothing to fix.</td></tr><tr><th>Issue type:</th><td>tba.</td></tr><tr><th>Fix type:</th><td>tba.</td></tr><tr><th>Fix version:</th><td>tba.</td></tr><tr><th>Fix release date:</th><td>tba.</td></tr></tbody></table>

**Issue confirmed for:**

*   None

**TODOs:**  
None

**Comment by GeheimagentNr1** [comment] 2022-10-09 08:13
What does your config file looks like?  
From the error message, it looks like, that the bot token is in the wrong place. It seems like, the bot token is in the place of the channel\_id or something like this. Because it wants to load a number, but gets a text.

**Comment by P4NC00Nexe** [comment] 2022-10-09 19:03
This is the config file
https://gist.github.com/P4NC00Nexe/7af2226f827ee326f2fc9ca276f76fc4

**Comment by GeheimagentNr1** [comment] 2022-10-09 19:58
For the value of the bot\_token at line 4 the " are missing.

**Comment by P4NC00Nexe** [comment] 2022-10-09 20:06
ok so i need to have quotation marks?

**Comment by GeheimagentNr1** [comment] 2022-10-09 21:43
Yes, like for the command_prexfix and the messages.

**Comment by P4NC00Nexe** [comment] 2022-10-09 22:27
Ah That worked. Thank you!

**Comment by P4NC00Nexe** [comment] 2022-10-09 22:36
So that got the server to launch but now im noticing that the discord commands dont work and message sent from discord dont show up in game, just the username.

**Comment by P4NC00Nexe** [comment] 2022-10-09 23:11
Ah nvm i looked through the comments on curseforge and found an answer

**Closed as completed** 2022-10-17 19:54 UTC
Labels: invalid
