### ISSUE TITLE
Minecraft->Discord chat messages don't work on Mohist server

### ISSUE THREAD

**Issue by Steveplays28** [GeheimagentNr1/DiscordIntegration#5] opened 2021-06-21 20:24 UTC
**Versions**
Minecraft Version: 1.16.5
Minecraft Mohist Version: 1.16.5-553
Mod Version: 2.0.0

**Log files**
[latest.log](https://github.com/GeheimagentNr1/DiscordIntegration/files/6689265/latest.log)

**Describe the bug**
I'm running a Mohist server instead of a standard Forge server. This is a hybrid server which allows you to run plugins and mods simultaneously. But, for some reason the Minecraft->Discord chat messages stop working.
If you send a chat message in Minecraft, it does not display in Discord. The rest of the bot does seem to work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install mod on Mohist server with plugins
2. Look and see

**Expected behaviour**
The message being shown in the Discord chat via the bot.

**Additional context**
I'm running the mod on a Mohist server with 45 mods and 5 plugins. The mods aren't the issue, this mod worked fine on the normal Forge server.

**Comment by GeheimagentNr1** [comment] 2021-06-22 14:14
<table><tbody><tr><th>Status:</th><td>Won't fix</td></tr><tr><th>Issue type:</th><td>tba</td></tr><tr><th>Fix type:</th><td>tba</td></tr><tr><th>Fix version:</th><td>tba</td></tr><tr><th>Fix release date:</th><td>tba</td></tr></tbody></table>

**Issue confirmed for:**

*   Minecraft version: 1.16.5  
    Minecraft Mohist Version: 666  
    Mod version: 2.0.0

**TODOs:**

*   [x] Recreate bug with:  
        Minecraft 1.16.5  
        Minecraft Mohist Version ~553~ 666  
        Mod Version 2.0.0
*   [x] Recreate bug with:  
        Minecraft 1.16,5  
        Forge 36.1.32  
        Mod Version 2.0.0

#### Comment:

The issue does not occur with "Vanilla" Forge (TODOs point 2).

**Comment by Steveplays28** [comment] 2021-06-24 07:11
I have something to add to this as well, it seems like the commands in Discord do not work either.
See this [image](https://user-images.githubusercontent.com/62797992/123218460-09eee480-d4cc-11eb-9b4a-05d41ce603c8.png).

**Comment by GeheimagentNr1** [comment] 2021-06-27 01:00
I have escalated your issue to Mohist: MohistMC/Mohist#1477  
If they don't fix the issues, that the ServerChatEvent is not fired and that the CommandSources to run Minecraft Commands has to be Bukkit and not only Vanilla/Forge CommandSources, then this bug will not be fixed.

Please read the Mohist Ticket MohistMC/Mohist#1477 and add more relevant information, if I forgot something or if you have something to add.

**Comment by GeheimagentNr1** [comment] 2023-03-26 20:55
Because this is an issue of Mohist and on of this mod, this ticket will be closed.

**Closed as completed by GeheimagentNr1** 2023-03-26 20:55 UTC
Labels: bug

**Comment by Steveplays28** [comment] 2023-03-27 13:30
No worries, thanks for your time. I no longer use Mohist nowadays.
